import { ProgramItem, EventItem, GalleryItem, NewsArticle, TestimonialItem, ImpactStat, TimelineItem } from '../types';

export const TRUST_INFO = {
  name: 'Sri Susheela Trust',
  tagline: 'Nurturing Hope, Empowering Communities, Serving Humanity',
  taglineTa: 'நம்பிக்கையை வளர்ப்போம், சமுதாயத்தை உயர்த்துவோம், மனிதநேயத்துடன் சேவையாற்றுவோம்',
  regNumber: 'REG-TN/2018/80G/12A/04928',
  taxBenefitNote: 'Donations to Sri Susheela Trust are 50% Tax Exempted under Section 80G of the Indian Income Tax Act.',
  establishedYear: '2018',
  email: 'contact@srisusheelatrust.org',
  phonePrimary: '+91 98401 23456',
  phoneSecondary: '+91 44 2834 5678',
  address: {
    street: 'No. 42, Sri Susheela Trust Building, Gandhi Road',
    area: 'T. Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600017',
    country: 'India',
  },
  socials: {
    facebook: 'https://facebook.com',
    instagram: 'https://instagram.com',
    twitter: 'https://twitter.com',
    youtube: 'https://youtube.com',
    whatsapp: 'https://wa.me/919840123456',
  },
  bankDetails: {
    accountName: 'Sri Susheela Trust',
    accountNumber: '3948 5720 1948',
    bankName: 'State Bank of India',
    branch: 'T. Nagar Branch, Chennai',
    ifsc: 'SBIN0000800',
    upiId: 'srisusheelatrust@sbi',
  },
};

export const MOCK_PROGRAMS: ProgramItem[] = [
  {
    id: 'annadhanam',
    title: 'Daily Annadhanam Initiative',
    titleTa: 'தினசரி அன்னதானத் திட்டம்',
    shortDesc: 'Providing nutritious, warm meals daily to the underprivileged, homeless, and hospital attendants.',
    shortDescTa: 'ஏழை எளியோர், வீடற்றோர் மற்றும் மருத்துவமனை உதவியாளர்களுக்கு தினமும் சத்தான உணவு வழங்கப்படுகிறது.',
    description: 'Food is the fundamental right of every human being. Through our Daily Annadhanam Initiative, we prepare and distribute over 1,500 hygienic, freshly cooked meals every single day across Chennai and surrounding rural districts.',
    descriptionTa: 'உணவு என்பது மனிதனின் அடிப்படை உரிமை. எங்கள் தினசரி அன்னதானத் திட்டத்தின் மூலம் தினமும் 1,500-க்கும் மேற்பட்ட சத்தான உணவுகள் வழங்கப்படுகின்றன.',
    category: 'annadhanam',
    iconName: 'Utensils',
    imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=1200&q=80',
    beneficiariesCount: '500,000+ Meals Served',
    features: ['Hygienic Mobile Kitchens', 'Special Festival Feeds', 'Hospital Ward Meal Distribution', 'Zero Food Waste Protocol'],
    featuresTa: ['சுகாதாரமான மொபைல் சமையலறை', 'சிறப்பு பண்டிகை விருந்துகள்', 'மருத்துவமனை உணவு விநியோகம்', 'உணவு வீணடிக்கப்படாமை'],
  },
  {
    id: 'education',
    title: 'Vidya Jyothi Free Education',
    titleTa: 'வித்யா ஜோதி இலவசக் கல்வி',
    shortDesc: 'Empowering children with scholarships, free learning kits, digital labs, and mentorship.',
    shortDescTa: 'குழந்தைகளுக்கு கல்வி உதவித்தொகை, கற்றல் உபகரணங்கள் மற்றும் கணினி பயிற்சி வழங்கப்படுகிறது.',
    description: 'We believe education breaks the cycle of poverty. Vidya Jyothi provides full academic scholarships, textbooks, uniforms, evening tuition centers, and coding labs for deserving students in rural schools.',
    descriptionTa: 'கல்வியே வறுமையை ஒழிக்கும் சாவி. இத்திட்டத்தின் மூலம் மாணவர்களுக்கு முழு கல்வி உதவித்தொகை மற்றும் பாடப்புத்தகங்கள் வழங்கப்படுகின்றன.',
    category: 'education',
    iconName: 'GraduationCap',
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80',
    beneficiariesCount: '3,200+ Students Supported',
    features: ['100% Tuition Scholarships', 'Free STEM & Computer Labs', 'After-School Learning Hubs', 'Career Guidance Mentorship'],
    featuresTa: ['100% கல்வி உதவித்தொகை', 'இலவச கணினி பயிற்சி', 'மாலை நேரக் கற்றல் மையங்கள்', 'வேலைவாய்ப்பு வழிகாட்டுதல்'],
  },
  {
    id: 'elderly',
    title: 'Anbu Illam Senior Care',
    titleTa: 'அன்பு இல்லம் முதியோர் அரவணைப்பு',
    shortDesc: 'Dignified shelter, healthcare, and emotional companionship for destitute senior citizens.',
    shortDescTa: 'ஆதரவற்ற முதியோருக்கு கண்ணியமான தங்குமிடம், மருத்துவம் மற்றும் அன்பான பராமரிப்பு.',
    description: 'Anbu Illam offers a safe, peaceful home for abandoned elderly citizens with 24/7 medical supervision, nutritious diets, recreational activities, and compassionate geriatric care.',
    descriptionTa: 'ஆதரவற்ற முதியோர்களுக்கு 24 மணி நேர மருத்துவப் பராமரிப்புடன் கூடிய அமைதியான தங்குமிடம் வழங்கப்படுகிறது.',
    category: 'elderly',
    iconName: 'HeartHandshake',
    imageUrl: 'https://images.unsplash.com/photo-1516307365426-bea591f05011?auto=format&fit=crop&w=1200&q=80',
    beneficiariesCount: '450+ Seniors Living Happily',
    features: ['Resident Doctor & Nurses', 'Physiotherapy & Yoga', 'Spiritual & Cultural Gatherings', 'Palliative & End-of-Life Care'],
    featuresTa: ['மருத்துவர் மற்றும் செவிலியர் குழு', 'இயற்கை மருத்துவம் & யோகா', 'ஆன்மீக நிகழ்வுகள்', 'அன்பான பராமரிப்பு'],
  },
  {
    id: 'healthcare',
    title: 'Arogya Sanjeevani Free Medical Camps',
    titleTa: 'ஆரோக்கிய சஞ்சீவனி இலவச மருத்துவ முகாமி',
    shortDesc: 'Mobile health clinics, free surgeries, eye checkups, and life-saving medications.',
    shortDescTa: 'கிராமப்புறங்களில் இலவச மருத்துவ பரிசோதனைகள், இலவச கண் அறுவை சிகிச்சைகள் மற்றும் மருந்துகள்.',
    description: 'Bringing specialist healthcare directly to remote villages. Our mobile medical vans conduct eye screening, diabetic care, dental health, and assist with complex surgeries through partner super-specialty hospitals.',
    descriptionTa: 'தொலைதூர கிராமங்களுக்கும் அதிநவீன மருத்துவ சேவைகளைக் கொண்டு சேர்க்கிறோம்.',
    category: 'healthcare',
    iconName: 'Stethoscope',
    imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80',
    beneficiariesCount: '85,000+ Patients Treated',
    features: ['Free Cataract Surgeries', 'Mobile Diagnostic Vans', 'Free Prescription Medicines', 'Maternal & Child Care'],
    featuresTa: ['இலவச கண் புரை அறுவைசிகிச்சை', 'மொபைல் பரிசோதனை வாகனம்', 'இலவச மருந்துகள் விநியோகம்', 'தாய் சேய் நல பராமரிப்பு'],
  },
  {
    id: 'empowerment',
    title: 'Women Self-Reliance Center',
    titleTa: 'மகளிர் சுயசார்பு தையல் & தொழிற்பயிற்சி',
    shortDesc: 'Tailoring, handicrafts, micro-finance support, and vocational skills for rural women.',
    shortDescTa: 'மகளிருக்கு இலவச தையற்பயிற்சி, கைவினைப் பொருட்கள் உற்பத்தி மற்றும் சுயதொழில் கடன் உதவி.',
    description: 'Transforming rural women into confident entrepreneurs. We provide certified training in commercial tailoring, embroidery, organic soap making, and assist with self-help group seed funding.',
    descriptionTa: 'கிராமப்புற பெண்களை தொழில்முனைவோராக மாற்றும் நோக்கில் தையற்பயிற்சி மற்றும் சுயதொழில் கடன் வழங்கப்படுகிறது.',
    category: 'empowerment',
    iconName: 'Sparkles',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80',
    beneficiariesCount: '1,800+ Women Empowered',
    features: ['Free Sewing Machine Grants', 'Quality Certification Courses', 'Market Linkage Support', 'Micro-Credit Assistance'],
    featuresTa: ['இலவச தையல் இயந்திரம்', 'சான்றிதழ் படிப்புகள்', 'சந்தை வாய்ப்புகள்', 'சுயதொழில் நிதி உதவி'],
  },
];

export const MOCK_EVENTS: EventItem[] = [
  {
    id: 'event-1',
    title: 'Mega Free Multi-Specialty Health Camp',
    titleTa: 'மெகா இலவச பன்முக மருத்துவ முகாம்',
    date: 'August 15, 2026',
    time: '08:30 AM - 04:00 PM',
    location: 'Sri Susheela Community Hall, Kanchipuram',
    locationTa: 'ஸ்ரீ சுசீலா சமுதாயக்கூடம், காஞ்சிபுரம்',
    shortDesc: 'Free Cardiology, Ophthalmology, Pediatrics, and Orthopedic consultations along with free medicine distribution.',
    shortDescTa: 'இலவச இதய நோய், கண், குழந்தைகள் மற்றும் எலும்பு சிகிச்சை பரிசோதனைகள் மற்றும் மருந்துகள்.',
    category: 'Healthcare',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    isUpcoming: true,
    registeredCount: 420,
  },
  {
    id: 'event-2',
    title: 'Educational Kit & Laptop Distribution Drive',
    titleTa: 'கல்வி உபகரணங்கள் மற்றும் மடிக்கணினி வழங்கும் விழா',
    date: 'September 5, 2026',
    time: '10:00 AM - 01:00 PM',
    location: 'Government Higher Secondary School Auditorium, Thiruvallur',
    locationTa: 'அரசு மேல்நிலைப்பள்ளி அரங்கம், திருவள்ளூர்',
    shortDesc: 'Distributing 500+ student learning kits and 50 refurbished laptops to underprivileged college scholars.',
    shortDescTa: '500+ மாணவர்களுக்கு இலவச பாடப்புத்தகங்கள் மற்றும் 50 மடிக்கணினிகள் வழங்கல்.',
    category: 'Education',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
    isUpcoming: true,
    registeredCount: 290,
  },
  {
    id: 'event-3',
    title: 'Grand Annadhanam Mahotsavam 2026',
    titleTa: 'மாபெரும் அன்னதான மஹோத்சவம் 2026',
    date: 'July 10, 2026',
    time: '07:00 AM - 08:00 PM',
    location: 'Sri Susheela Trust Headquarters, Chennai',
    locationTa: 'ஸ்ரீ சுசீலா அறக்கட்டளை தலைமையகம், சென்னை',
    shortDesc: 'Served traditional festive banana leaf feast for over 10,000 people in a single day.',
    shortDescTa: 'ஒரே நாளில் 10,000-க்கும் மேற்பட்டோருக்கு பாரம்பரிய வாழை இலை விருந்து உபசரிப்பு.',
    category: 'Annadhanam',
    imageUrl: 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=800&q=80',
    isUpcoming: false,
    registeredCount: 10500,
  },
];

export const MOCK_GALLERY: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Daily Annadhanam Meal Serving',
    titleTa: 'தினசரி அன்னதான உணவு விநியோகம்',
    category: 'annadhanam',
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=600&q=80',
    description: 'Volunteers distributing warm nutritious food to beneficiaries.',
  },
  {
    id: 'gal-2',
    title: 'Vidya Jyothi Digital Lab Launch',
    titleTa: 'டிஜிட்டல் கணினி ஆய்வகம் தொடக்கம்',
    category: 'education',
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=600&q=80',
    description: 'Children exploring interactive coding and science modules.',
  },
  {
    id: 'gal-3',
    title: 'Eye Surgery Mobile Camp',
    titleTa: 'கண் பரிசோதனை மருத்துவ முகாம்',
    category: 'healthcare',
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=600&q=80',
    description: 'Senior citizens receiving free vision care and spectacles.',
  },
  {
    id: 'gal-4',
    title: 'Anbu Illam Cultural Evening',
    titleTa: 'அன்பு இல்லம் கலாச்சார விழா',
    category: 'events',
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1516307365426-bea591f05011?auto=format&fit=crop&w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516307365426-bea591f05011?auto=format&fit=crop&w=600&q=80',
    description: 'Elderly residents enjoying traditional music performances.',
  },
  {
    id: 'gal-5',
    title: 'Tailoring Machines Distribution',
    titleTa: 'இலவச தையல் எந்திரம் வழங்குதல்',
    category: 'community',
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    description: 'Empowering women with self-reliant livelihood tools.',
  },
  {
    id: 'gal-6',
    title: 'Community Tree Plantation Drive',
    titleTa: 'மரக்கன்றுகள் நடும் விழா',
    category: 'community',
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80',
    description: 'Planting 2,000 native saplings in rural school campuses.',
  },
];

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: 'news-1',
    title: 'Sri Susheela Trust Recognized with State Excellence Award for Annadhanam Services',
    titleTa: 'ஸ்ரீ சுசீலா அறக்கட்டளைக்கு மாநில சிறந்த சமூக சேவை விருது',
    publishedDate: 'June 20, 2026',
    category: 'Recognition',
    excerpt: 'The Honorable State Minister commended Sri Susheela Trust for serving over 500,000 meals to needy communities during peak crisis times.',
    excerptTa: '5 லட்சம் பேருக்கு மேல் அன்னதானம் வழங்கிய ஸ்ரீ சுசீலா அறக்கட்டளைக்கு அமைச்சரின் பாராட்டு விருது.',
    content: 'Sri Susheela Trust has been bestowed with the State Social Excellence Award 2026 in recognition of its unremitting dedication to eradicating hunger through its Daily Annadhanam Initiative.',
    contentTa: 'பசி இல்லாத சமுதாயத்தை உருவாக்க பாடுபடும் ஸ்ரீ சுசீலா அறக்கட்டளைக்கு 2026 ஆம் ஆண்டிற்கான சிறந்த விருதை அரசு வழங்கியுள்ளது.',
    imageUrl: 'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?auto=format&fit=crop&w=800&q=80',
    readTime: '3 min read',
    author: 'Editorial Team',
  },
  {
    id: 'news-2',
    title: 'New Digital Learning Center Opened in Rural Kanchipuram School',
    titleTa: 'காஞ்சிபுரம் கிராமப்புற பள்ளியில் புதிய டிஜிட்டல் கற்றல் மையம்',
    publishedDate: 'May 12, 2026',
    category: 'Education',
    excerpt: 'Equipped with 25 high-speed computer systems, smart boards, and internet connectivity for 600 rural students.',
    excerptTa: '600 மாணவர்களுக்காக 25 கணினிகள் மற்றும் ஸ்மார்ட் போர்டுகளுடன் கூடிய புதிய மையம்.',
    content: 'Continuing our promise of democratizing education, Sri Susheela Trust inaugurated its 12th Vidya Jyothi Digital Learning Center at Government School Kanchipuram.',
    contentTa: 'கிராமப்புற மாணவர்களுக்கும் கணினி அறிவியல் கல்வியை இலவசமாக கொண்டு சேர்க்கும் முயற்சி தொடர்ந்து நடைபெறுகிறது.',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
    readTime: '4 min read',
    author: 'Vidya Jyothi Team',
  },
];

export const MOCK_TESTIMONIALS: TestimonialItem[] = [
  {
    id: 't-1',
    name: 'R. Lakshmi Ammal',
    role: 'Anbu Illam Resident (Age 74)',
    roleTa: 'அன்பு இல்லப் பயனாளி (வயது 74)',
    quote: 'After losing my family, I felt completely abandoned. Sri Susheela Trust gave me not just shelter, but a warm family filled with love, medical care, and respect.',
    quoteTa: 'குடும்பத்தை இழந்த பின் எனக்கு வாழ்வே இருண்டது. ஸ்ரீ சுசீலா அறக்கட்டளை எனக்கு தங்குமிடம் மட்டுமின்றி, அன்பு நிறைந்த குடும்பத்தையும் தந்தது.',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    rating: 5,
    location: 'Chennai',
  },
  {
    id: 't-2',
    name: 'K. Karthikeyan',
    role: 'Vidya Jyothi Scholar (Engineering Student)',
    roleTa: 'வித்யா ஜோதி அம்மா மாணவர்',
    quote: 'Without the full scholarship and laptop from Sri Susheela Trust, my dream of pursuing Computer Science Engineering would have remained impossible.',
    quoteTa: 'இலவச கல்வி உதவித்தொகை மற்றும் கணினி கிடைக்காமல் போயிருந்தால் என் பொறியியல் கனவு நனவாகியிருக்காது.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    rating: 5,
    location: 'Thiruvallur',
  },
  {
    id: 't-3',
    name: 'Dr. S. Sundaram, MD',
    role: 'Chief Medical Volunteer',
    roleTa: 'தலைமை மருத்துவ ஆலோசகர்',
    quote: 'I have volunteered in numerous camps, but the organization, dignity, and sincerity of Sri Susheela Trust team is truly world-class.',
    quoteTa: 'ஸ்ரீ சுசீலா அறக்கட்டளையின் நேர்மையும் அர்ப்பணிப்பும் மருத்துவ முகாம்களை மிகச்சிறப்பாக நடத்த உதவுகிறது.',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80',
    rating: 5,
    location: 'Coimbatore',
  },
];

export const MOCK_IMPACT_STATS: ImpactStat[] = [
  {
    id: 'meals',
    value: 500000,
    suffix: '+',
    label: 'Nutritious Meals Served',
    labelTa: 'வழங்கப்பட்ட அன்னதான உணவுகள்',
    description: 'Freshly prepared hot meals served through mobile vans & daily kitchens.',
    descriptionTa: 'தினசரி சத்தான சூடான உணவுகள் விநியோகம்.',
    iconName: 'Utensils',
  },
  {
    id: 'students',
    value: 3200,
    suffix: '+',
    label: 'Students Educated',
    labelTa: 'பயனடைந்த மாணவர்கள்',
    description: 'Full scholarships, uniforms, textbooks, and digital skill training.',
    descriptionTa: 'முழு கல்வி உதவித்தொகை மற்றும் புத்தகங்கள்.',
    iconName: 'GraduationCap',
  },
  {
    id: 'patients',
    value: 85000,
    suffix: '+',
    label: 'Patients Treated',
    labelTa: 'பயனடைந்த நோயாளிகள்',
    description: 'Free health checkups, cataract surgeries, and medications.',
    descriptionTa: 'இலவச மருத்துவ பரிசோதனை மற்றும் சிகிச்சை.',
    iconName: 'Stethoscope',
  },
  {
    id: 'seniors',
    value: 450,
    suffix: '+',
    label: 'Seniors Sheltered',
    labelTa: 'அரவணைக்கப்பட்ட முதியோர்',
    description: 'Compassionate elderly care, housing, and 24/7 medical supervision.',
    descriptionTa: 'பாதுகாப்பான தங்குமிடம் மற்றும் மருத்துவப் பராமரிப்பு.',
    iconName: 'HeartHandshake',
  },
];

export const MOCK_TIMELINE: TimelineItem[] = [
  {
    year: '2018',
    title: 'Inception of Sri Susheela Trust',
    titleTa: 'ஸ்ரீ சுசீலா அறக்கட்டளை தொடக்கம்',
    description: 'Founded with a noble vision to serve free meals to 50 destitute individuals daily in Chennai.',
    descriptionTa: 'சென்னையில் 50 ஏழைகளுக்கு தினமும் இலவச உணவு வழங்கும் நோக்குடன் தொடங்கப்பட்டது.',
    badge: 'Foundation',
  },
  {
    year: '2020',
    title: 'COVID Crisis Relief Operations',
    titleTa: 'கொரோனா நிவாரணப் பணிகள்',
    description: 'Distributed 150,000+ emergency food packets and medical kits to daily wage workers.',
    descriptionTa: '1.5 லட்சம் பேருக்கு மேல் அவசர உணவுப் பொட்டலங்கள் மற்றும் மருத்துவ பொருட்கள் வழங்கப்பட்டது.',
    badge: 'Crisis Relief',
  },
  {
    year: '2022',
    title: 'Launch of Vidya Jyothi & Anbu Illam',
    titleTa: 'வித்யா ஜோதி & அன்பு இல்லம் திட்டம்',
    description: 'Expanded into structured educational scholarships and opened a sanctuary for abandoned seniors.',
    descriptionTa: 'கல்வி உதவித்தொகை மற்றும் முதியோர் இல்லம் رسمی தொடங்கப்பட்டது.',
    badge: 'Expansion',
  },
  {
    year: '2024',
    title: 'Mobile Healthcare Fleet',
    titleTa: 'மொபைல் மருத்துவ வாகனங்கள்',
    description: 'Deployed 3 custom mobile clinic vans serving 40+ remote villages in Tamil Nadu.',
    descriptionTa: '40 கிராமப்புற பகுதிகளுக்கு இலவச மருத்துவ வாகன சேவை விரிவுபடுத்தப்பட்டது.',
    badge: 'Innovation',
  },
  {
    year: '2026',
    title: 'Target: 1 Million Beneficiaries',
    titleTa: 'இலக்கு: 10 லட்சம் பயனாளிகள்',
    description: 'Building a integrated mega social service complex with green energy and solar kitchens.',
    descriptionTa: 'சூரிய மின்சக்தி சமையலறையுடன் கூடிய மாபெரும் ஒருங்கிணைந்த சமூக சேவை மையம் உருவாக்கம்.',
    badge: 'Milestone',
  },
];
